new PA cleanups

diff --git a/runtest b/runtest
--- a/runtest
+++ b/runtest
@@ -128,7 +128,13 @@ if [ $(expr "$file" : ".*_errors") -gt 0 ]; then
     exit 0
 fi
 
+rm -f $testdir/$name.tfa
 run $P4C $P4C_ARGS $file -o $testdir/$name.tfa || die
+
+if [ ! -r $testdir/$name.tfa ]; then
+    echo >&2 "$P4C did not give an error but did not generate output either"
+    exit 1
+fi
 
 if [ -r ${file%.p4}.stf ]; then
     TFAS=$(findbin tofino-asm tfas)
