Update ref for model update (#2508)
* Update regs to 20181114_132632_78799_main_jbay
* Ref points update for model update
* PTF test dependency (need to move these to ptf docker image at some point)
* Split the bf-switch tests as hostif tests are failing (merge into single set in the next PR)
* Add switch_16 for JBay compile only (many PTF tests are failing, consider adding to our regression once the tests are stable)

diff --git a/p4-tests/runtest b/p4-tests/runtest
--- a/p4-tests/runtest
+++ b/p4-tests/runtest
@@ -593,7 +593,10 @@ configure_p4_build() {
     if $verbose ; then
         tail -n 10 ${testout}/p4-build-conf.log
     fi
-    run make install > ${testout}/p4-build-make.log || die
+    run make > ${testout}/p4-build-make.log || die
+    # make install fails for bf-switch for subsequent test sets
+    # TODO: fix this during refactor of runtest
+    run make install > ${testout}/p4-build-make_install.log
 }
 
 if $run_pd ; then
