Add ability to use custome PTF test directory
As opposed to default behavior, which is to look for the existence of
the `<P4_source_dir>/<P4_source_name>.ptf` directory and use it. This
default behavior is inconvenient for programs like tor.p4, which are in
a submodule, as the PTF tests are expected to be updated more frequently
than the P4 source. In some cases we may also not have control over the
submodule containing the P4 source.

diff --git a/p4-tests/runtest b/p4-tests/runtest
--- a/p4-tests/runtest
+++ b/p4-tests/runtest
@@ -23,6 +23,7 @@ debug=false
 run_stf=true
 run_stf2ptf=false
 run_ptf=false
+ptftestdir=""
 
 die() {
     if [ $# -gt 0 ]; then
@@ -113,6 +114,7 @@ while [ $# -gt 1 ]; do
         echo >&2 "   -time          time commands as they run"
         echo >&2 "   -to <sec>      timeout programs after <sec> seconds (default 30)"
         echo >&2 "   -ptf           run PTF tests if available"
+        echo >&2 "   -ptfdir <dir>  directory containing PTF tests"
         echo >&2 "other arguments passed to p4c-tofino:"
         $P4C --help
         exit 0
@@ -135,6 +137,10 @@ while [ $# -gt 1 ]; do
         ;;
     -ptf)
         run_ptf=true
+        ;;
+    -ptfdir)
+        ptftestdir=$2
+        shift
         ;;
     -stf2ptf)
         run_stf2ptf=true
@@ -214,10 +220,15 @@ else
     fi
 fi
 
-ptftestdir=${file%.p4}.ptf
-if [ ! -d ${ptftestdir} ] && ! $run_stf2ptf; then
-    # no ptf to run
-    run_ptf=false
+if [ "$ptftestdir" != "" ] && [ ! -d ${ptftestdir} ]; then
+    die "Invalid -ptfdir: $ptftestdir does not exist"
+fi
+if [ "$ptftestdir" = "" ]; then
+    ptftestdir=${file%.p4}.ptf
+    if [ ! -d ${ptftestdir} ] && ! $run_stf2ptf; then
+        # no ptf to run
+        run_ptf=false
+    fi
 fi
 
 p4runtime_out=$testdir/${name}${out_ext}.out/p4info.proto.txt
