adds checking of walle return code and pyinstaller version (#662)
* adds checking of walle return code and pyinstaller version

bflink was ignoring the return code from walle, causing script
havoc as the compilation process went ahead without a tofino.bin.

The main cause of failure is the broken version of pyinstaller, so
we added a check to make sure that we install a version that is correct.

* fixes pyinstaller version in Dockerfiles

* fix xfails

Also remove incorrectly placed pragma in test case

diff --git a/bf-asm/bflink b/bf-asm/bflink
--- a/bf-asm/bflink
+++ b/bf-asm/bflink
@@ -140,6 +140,7 @@ fi
 
 #echo "$WALLE --target $CHIP $schema_arg -o $OUT $objs $pipe_args"
 $WALLE --target $CHIP $schema_arg -o $OUT $objs $pipe_args
+rc=$?
 
 # cleanup
 output_dir=$(dirname $OUT)
@@ -160,3 +161,6 @@ fi
 if [ -d "$tmpdir" ]; then
     rm -rf $tmpdir
 fi
+
+# exit with a return code if walle failed
+exit $rc
