Debian packaging with cpack (#432)
* packaging and versioning

* compile JBay optionally in assembler

Introduces HAVE_JBAY as a configuration time macro that can be enabled
using -DENABLE_JBAY=ON when running cmake to optionally compile JBay
into the assembler.

Also removes the installation of chip.schema which are not needed for
generating binaries (just for register templates) and removes it as a
parameter that is passed to walle by the p4c driver.

* Add missing HAVE_JBAY include guard

Change CPACK_STRIP_FILES ON to CPACK_STRIP_FILES TRUE

Update p4c submodule ref point

Add LICENSE and README

* bundles chip.schema with walle executable

Using pyinstaller's add-data feature to bundle the schema files with
the walle executable in the lib/<chip>/chip.schema.

We add a --target <chip_name> argument to walle (and tflink) to allow
us to retrieve the schema.

To find the file, we check whether we're running as a bundle (see
https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#run-time-information).
Pyinstaller sets the frozen attribute, and the sys._MEIPASS variable
to the root directory of the bundle. We then set the appropriate path
for the schema using the chip argument.

walle still accepts a --schema argument so that an explicit file can
be passed. It is overwritten when bundled, but can be used when
running out of the python source -- so we can merge these changes in
all the other numerous copies of walle.

tflink no longer needs to search the path for the schema, because in
our setup it always uses the bundled version. p4c.tofino.cfg is now
invoking tflink with a --target argument. I also removed the find_file
from tflink, it should always be invoked with an explicit walle
executable (whether python or bundled), and changed both places where
it was called: p4c driver and bf-asm/test/runtests. Couldn't find
other instances, but we should keep an eye for them.

* Removing README from dockerignore

So that Cpack does not complain.

diff --git a/bf-asm/tflink b/bf-asm/tflink
--- a/bf-asm/tflink
+++ b/bf-asm/tflink
@@ -1,28 +1,7 @@
 #!/bin/sh
 
-READLINK=readlink
-if [ `uname -s` = "Darwin" ]; then
-    READLINK=greadlink
-fi
-
-script=$($READLINK -f $0)
-
-findfile () {
-    dir=$(dirname $script)
-    while [ "$dir" != "/" ]; do
-        if [ -f "$dir/$1" ]; then
-            echo "$dir/$1"
-            return
-        fi
-        if [ "$dir" = "." ]; then
-            dir=$(pwd -P)
-        fi
-        dir=$(dirname $dir)
-    done
-}
-
 WALLE=""
-SCHEMA=""
+CHIP="tofino"
 OUT="tofino.bin"
 objs=""
 tmpdir=""
@@ -43,11 +22,11 @@ while [ $# -gt 0 ]; do
     -o)
         OUT="$2"
         shift ; shift ;;
-    --schema|-s)
-        SCHEMA="$2"
-        shift ; shift ;;
     --walle|-w)
         WALLE="$2"
+        shift ; shift ;;
+    --target|-t)
+        CHIP="$2"
         shift ; shift ;;
     *.json.Z)
         if [ -z "$tmpdir" ]; then
@@ -91,32 +70,16 @@ while [ $# -gt 0 ]; do
 done
 
 if [ ! -x "$WALLE" ]; then
-    WALLE=$(findfile walle/walle.py)
-    if [ ! -x "$WALLE" ]; then
-        WALLE=$(findfile walle/walle/walle.py)
+    if [ -e "$WALLE" ]; then
+        echo "$WALLE must be executable"
+    else
+        echo "4: $WALLE"
+        echo >&2 "Can't find walle"
     fi
-    if [ ! -x "$WALLE" ]; then
-        if [ -e "$WALLE" ]; then
-            echo "$WALLE must be executable"
-        else
-            echo "4: $WALLE"
-            echo >&2 "Can't find walle"
-        fi
-        exit 1
-    fi
-fi
-if [ ! -r "$SCHEMA" ]; then
-    SCHEMA=$(findfile chip.schema)
-    if [ ! -r "$SCHEMA" ]; then
-        SCHEMA=$(findfile tofino/chip.schema)
-    fi
-    if [ ! -r "$SCHEMA" ]; then
-        echo >&2 "Can't find chip schema"
-        exit 1
-    fi
+    exit 1
 fi
 
-$WALLE --schema $SCHEMA -o $OUT $objs
+$WALLE --target $CHIP -o $OUT $objs
 
 if [ -d "$tmpdir" ]; then
     rm -rf $tmpdir
